### ISSUE TITLE
X replays

### ISSUE THREAD

**Issue by SpookyBear0** [Wieku/danser-go#30] opened 2020-08-14 17:42 UTC
I heard about this in the comment section of your videos, and I was wondering if that was public yet or im just looking in the wrong spot.

**Comment by Wieku** [comment] 2020-08-14 17:58
It's not public yet. Kinda duplicate of #18

**Closed by Wieku** 2020-08-14 17:58 UTC

**Comment by SpookyBear0** [comment] 2020-08-14 18:32
I see, thanks.
