### ISSUE TITLE
Panic: Runtime error: invalid memory address

### ISSUE THREAD

**Issue by MierenManz** [Wieku/danser-go#32] opened 2020-08-20 06:43 UTC
everytime i try to run danser-go with autohotkey(run %Comspec% /k C:\Users\User\Desktop\ree\danser.exe -d="owo2") I get the following error

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x51f205]

goroutine 1 [running, locked to thread]:
image.(*NRGBA).Bounds(0x0, 0x4, 0x4, 0xc004ae4020, 0x4)
        C:/Go/src/image/image.go:283 +0x5
github.com/go-gl/glfw/v3.2/glfw.(*Window).SetIcon(0xc006d28000, 0xc000085a70, 0x4, 0x4)
        C:/Users/Wieku/go/src/github.com/go-gl/glfw/v3.2/glfw/window.go:354 +0x111
main.run.func1()
        C:/Users/Wieku/go/src/github.com/wieku/danser/main.go:146 +0xbd9
github.com/faiface/mainthread.Call.func1()
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:63 +0x36
github.com/faiface/mainthread.Run(0x9fa988)
        C:/Users/Wieku/go/src/github.com/faiface/mainthread/mainthread.go:44 +0xc4
main.main()
        C:/Users/Wieku/go/src/github.com/wieku/danser/main.go:257 +0x4f

**Comment by Wieku** [comment] 2020-08-20 11:47
Duplicate of #23 
As a temp fix first cd to danser's location and then launch the exe.

**Closed by Wieku** 2020-08-20 11:47 UTC
