### ISSUE TITLE
Knockout not working

### ISSUE THREAD

**Issue by MostlyGhostlyYT** [Wieku/danser-go#69] opened 2021-01-15 18:43 UTC
**Describe the bug**
Hi,

I am trying to do a knockout and I can not get it to work, every time I try to do a knockout it just loads up normal danser.

idk why it doesn't work so if someone can help me that would be greatly appreciated

**Computer configuration:**
Operating System: Windows 10 Home
CPU: AMD RYZEN 5 4600H
GPU: GTX1650TI

**Comment by Wieku** [comment] 2021-01-15 18:47
Did you follow this? https://github.com/Wieku/danser-go/wiki/Knockout

**Comment by MostlyGhostlyYT** [comment] 2021-01-15 18:52
yes I did but it doesn't recognize I have replay files in the folder

**Comment by spookybear0** [comment] 2021-01-15 18:53
Are you using the `-knockout` flag?

**Comment by MostlyGhostlyYT** [comment] 2021-01-15 18:54
> Are you using the `-knockout` flag?

yes

**Comment by Wieku** [comment] 2021-01-15 18:55
Please send the logs. Most probably you're hitting wrong map.

**Comment by MostlyGhostlyYT** [comment] 2021-01-15 18:56
[danser.log](https://github.com/Wieku/danser-go/files/5822462/danser.log)

**Comment by Wieku** [comment] 2021-01-15 18:57
You didn't use `-knockout` flag...

**Comment by MostlyGhostlyYT** [comment] 2021-01-15 18:57
wrong log

**Comment by MostlyGhostlyYT** [comment] 2021-01-15 18:57
[danser.log](https://github.com/Wieku/danser-go/files/5822466/danser.log)

**Comment by Wieku** [comment] 2021-01-15 18:59
Oh, kina duplicate of #66 

As a workaround create folder named `2771923d14b96d887b3b99c74933d868` inside replays folder and run danser again

**Closed by Wieku** 2021-01-15 18:59 UTC
Labels: question
