### ISSUE TITLE
Knockout mode fails to render properly in middle of beatmap

### ISSUE THREAD

**Issue by thegreatestminer** [Wieku/danser-go#111] opened 2021-05-04 14:19 UTC
**Describe the bug**
While playing https://osu.ppy.sh/beatmapsets/934522#osu/1951034 in knockout mode with the top 50 replays, at around 38 seconds in, the following occurs:
 - The top four players fail to fully render.
 - The scoring symbols have strange lines.
 - The keypress circle are no longer fully rendered.

I am using the [clearblack](https://osuskins.net/skin/lwteH8H) skin, however this occurs on the default skin as well.

**Screenshots**
![image](https://user-images.githubusercontent.com/19188146/117016495-c55f7d80-acc0-11eb-80fc-9d4dd27908c9.png)

**Logs**
[danser - Copy.log](https://github.com/Wieku/danser-go/files/6421639/danser.-.Copy.log)

**Computer configuration:**
Operating System: Windows 10
CPU: Intel i5-8400
GPU: Intel UHD Graphics 630

**Comment by Wieku** [comment] 2021-05-04 14:21
Can you send a pack of those replays? Will be handy

**Comment by thegreatestminer** [comment] 2021-05-04 15:13
Here you go.
[cfefa0c0e217b6efa8fe19d660bb4e47.zip](https://github.com/Wieku/danser-go/files/6422077/cfefa0c0e217b6efa8fe19d660bb4e47.zip)

**Comment by Wieku** [comment] 2021-05-04 15:27
![danser_2021-05-04_17-26-30](https://user-images.githubusercontent.com/5307179/117028353-edb99d00-acfd-11eb-9fb0-091a169166a6.png)

Can't reproduce, can you share your settings as well?

**Comment by thegreatestminer** [comment] 2021-05-04 15:29
had to rename because github doesn't .json for whatever reason
[settings.txt](https://github.com/Wieku/danser-go/files/6422185/settings.txt)

**Comment by Wieku** [comment] 2021-05-04 15:45
Unfortunately I can't reproduce it, have you tried to update Intel Graphics Drivers? Seems like a driver issue

**Comment by thegreatestminer** [comment] 2021-05-04 16:12
I have not yet, but I'll try later today.

**Comment by vladaad** [comment] 2021-05-04 16:47
Reproduced on drivers `27.20.100.9168` and `27.20.100.9466` on HD Graphics 500 (Celeron N3450) with Windows 10 1809 (LTSC 2019)

**Comment by Wieku** [comment] 2021-05-04 17:56
Managed to reproduce on intel uhd620 gpu with `27.20.100.8476` drivers

**Comment by Wieku** [comment] 2021-05-05 12:17
Should be fixed with next release

**Closed** 2021-05-16 01:07 UTC
Labels: bug, fixed-in-dev, intel
