### ISSUE TITLE
Audio is cut after beatmap ends.

### ISSUE THREAD

**Issue by PercyDan54** [Wieku/danser-go#148] opened 2021-06-30 04:17 UTC
**Describe the bug**
Videos recorded with danser have audio shorter than the video
This doesn't affect me playing the video, but I got an error when uploading the video to a platform, it saids:
Failed to encode: The length of video/audio is incorrect

**Screenshots**
![image](https://user-images.githubusercontent.com/50285552/123901073-e5e44500-d99c-11eb-98fe-58d19769040c.png)
![image](https://user-images.githubusercontent.com/50285552/123901099-f2689d80-d99c-11eb-88a0-a387ab249a0b.png)
![image](https://user-images.githubusercontent.com/50285552/123901120-fe545f80-d99c-11eb-9b73-a06dbba08291.png)

**Comment by Wieku** [comment] 2021-06-30 09:11
Duplicate of #121 
Also don't use shitty platforms.

**Closed by Wieku** 2021-06-30 09:11 UTC
