### ISSUE TITLE
osulazer scores with relax do not render properly

### ISSUE THREAD

**Issue by Quicksoapy** [Wieku/danser-go#329] opened 2023-05-26 15:09 UTC
**Describe the bug**
Relax scores on lazer are not recorded correctly. Stable scores work fine on exact same setup.
This is the replay:
[Quicksoapy_playing_Camellia_-__ERABY_E_CONNEC_10N_IntegerTempest_OU_W0RLD_D1REC_10N_2023-05-02_22-52.txt](https://github.com/Wieku/danser-go/files/11576598/Quicksoapy_playing_Camellia_-__ERABY_E_CONNEC_10N_IntegerTempest_OU_W0RLD_D1REC_10N_2023-05-02_22-52.txt)
(Renamed it to .txt because github doesn't allow .osr apparently)

**Screenshots**
This is the actual score:
![osu_2023-05-26_16-59-15](https://github.com/Wieku/danser-go/assets/73587977/9f7764eb-fc95-4ab4-8bf6-e330b7154a86)

this is what danser creates:
![image](https://github.com/Wieku/danser-go/assets/73587977/cb300c56-13d0-49b5-a283-ab4470fa2a1e)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/11576560/danser.log)

**Computer configuration:**
Operating System: Linux Mint 21.1
CPU: AMD Ryzen 7 7700X

**Comment by Wieku** [comment] 2023-05-26 16:27
Learn how to open issues.

Duplicate of #302

**Closed by Wieku** 2023-05-26 16:27 UTC
