### ISSUE TITLE
Audio codec "aac" does not exist

### ISSUE THREAD

**Issue by timofey260** [Wieku/danser-go#144] opened 2021-06-23 17:44 UTC
**Describe the bug**
Iam trying to record a video, but it gives me error

**Screenshots**
![изображение_2021-06-23_203329](https://user-images.githubusercontent.com/69044246/123142580-45ed5f80-d462-11eb-898b-22c914883064.png)

**Logs**
[danser.log](https://github.com/Wieku/danser-go/files/6703863/danser.log)

**cmd log**

C:\Users\TiMoFey>F:\Desktop\dancer\danser.exe -t="Q" -record
2021/06/23 20:30:08 Checking GitHub for a new version of danser...
2021/06/23 20:30:08 You're using the newest version of danser.
2021/06/23 20:30:08 DatabaseManager: Initializing database...
2021/06/23 20:30:08 DatabaseManager: Database schema version: 20210423
2021/06/23 20:30:08 DatabaseManager: Database data version: 20210423
2021/06/23 20:30:08 DatabaseManager: Scanning "C:\Users\TiMoFey\AppData\Local\osu!\Songs" for .osu files...
2021/06/23 20:30:08 DatabaseManager: Scan complete. Found 1335 files.
2021/06/23 20:30:08 DatabaseManager: Comparing files with database...
2021/06/23 20:30:08 DatabaseManager: New beatmap found: Cuked - This Game (TV Size) (Cuked) [You Know... normal].osu
2021/06/23 20:30:08 DatabaseManager: New beatmap found: Sarah Connor - Cold As Ice (PH Electro Nightcore Mix) (Gologle) [Infamous Hype].osu
2021/06/23 20:30:08 DatabaseManager: Compare complete.
2021/06/23 20:30:08 DatabaseManager: Starting import of 2 maps...
2021/06/23 20:30:08 DatabaseManager: Importing: 358119 Sarah Connor - Cold As Ice (PH Electro Nightcore Mix)\Sarah Connor - Cold As Ice (PH Electro Nightcore Mix) (Gologle) [Infamous Hype].osu
2021/06/23 20:30:08 DatabaseManager: Importing: 229249 Cuked - This Game (TV Size)\Cuked - This Game (TV Size) (Cuked) [You Know... normal].osu
2021/06/23 20:30:08 DatabaseManager: Failed to import: 358119 Sarah Connor - Cold As Ice (PH Electro Nightcore Mix)\Sarah Connor - Cold As Ice (PH Electro Nightcore Mix) (Gologle) [Infamous Hype].osu
2021/06/23 20:30:08 DatabaseManager: Failed to import: 229249 Cuked - This Game (TV Size)\Cuked - This Game (TV Size) (Cuked) [You Know... normal].osu
2021/06/23 20:30:08 DatabaseManager: Imported 0 new/updated beatmaps. Inserting to database...
2021/06/23 20:30:08 DatabaseManager: Insert complete.
2021/06/23 20:30:08 DatabaseManager: Loading beatmaps from database...
2021/06/23 20:30:08 DatabaseManager: Loaded 1211 total.
2021/06/23 20:30:08 Initializing GLFW...
2021/06/23 20:30:08 GLFW initialized!
2021/06/23 20:30:08 GL Vendor:     Intel
2021/06/23 20:30:08 GL Renderer:   Intel(R) HD Graphics 620
2021/06/23 20:30:08 GL Version:    3.3.0 - Build 27.20.100.8681
2021/06/23 20:30:08 GLSL Version:  3.30 - Build 27.20.100.8681
2021/06/23 20:30:08 GL Extensions: GL_3DFX_texture_compression_FXT1 GL_AMD_depth_clamp_separate GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_cl_event GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_robustness_isolation GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_separate_stencil GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_packed_pixels GL_EXT_polygon_offset_clamp GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shader_framebuffer_fetch GL_EXT_shader_integer_mix GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture3D GL_EXT_texture_array GL_EXT_texture_compression_s3tc GL_EXT_texture_edge_clamp GL_EXT_texture_env_add GL_EXT_texture_env_combine GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_storage GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_IBM_texture_mirrored_repeat GL_INTEL_conservative_rasterization GL_INTEL_fragment_shader_ordering GL_INTEL_framebuffer_CMAA GL_INTEL_map_texture GL_INTEL_multi_rate_fragment_shader GL_INTEL_performance_query GL_KHR_blend_equation_advanced GL_KHR_blend_equation_advanced_coherent GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_texture_compression_astc_hdr GL_KHR_texture_compression_astc_ldr GL_NV_blend_square GL_NV_conditional_render GL_NV_primitive_restart GL_NV_texgen_reflection GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_SUN_multi_draw_arrays GL_WIN_swap_hint WGL_EXT_swap_control
2021/06/23 20:30:08 OpenGL initialized!
2021/06/23 20:30:09 Exo 2 Bold loaded!
2021/06/23 20:30:09 Initializing BASS...
2021/06/23 20:30:09 BASS Initialized!
2021/06/23 20:30:09 BASS Version:        2.4.15.26
2021/06/23 20:30:09 BASS FX Version:     2.4.12.1
2021/06/23 20:30:09 BASS Mix Version:    2.4.10.0
2021/06/23 20:30:09 BASS Encode Version: 2.4.14.0
2021/06/23 20:30:09 SkinManager: Loading skin: timofeyskin
2021/06/23 20:30:09 SkinManager: Skin "timofeyskin" loaded.
2021/06/23 20:30:09 Loading texture into atlas: assets/textures/cursor.png
2021/06/23 20:30:09 Loading texture into atlas: assets/textures/cursor-top.png
2021/06/23 20:30:09 Loading texture into atlas: assets/default-skin/hit0-0.png
2021/06/23 20:30:09 Loading texture into atlas: assets/default-skin/hit50.png
2021/06/23 20:30:09 Loading texture into atlas: assets/default-skin/hit100.png
2021/06/23 20:30:09 Loading texture into atlas: assets/textures/triangle.png
2021/06/23 20:30:09 Loading texture into atlas: assets/textures/triangle-shadow.png
2021/06/23 20:30:09 Loading texture into atlas: assets/textures/triangle-small.png
2021/06/23 20:30:09 Loading texture: assets/textures/cursortrail.png
2021/06/23 20:30:09 Playing: Kaede To Kyo Aki Ame Kuzu - Q [Hard]
2021/06/23 20:30:09 Loading texture into atlas: assets/textures/warning.png
2021/06/23 20:30:10 Trying to load storyboard from:  C:\Users\TiMoFey\AppData\Local\osu!\Songs\1316097 Kaede To Kyo Aki Ame Kuzu - Q\Kaede To Kyo Aki Ame Kuzu - Q (Abelia) [Hard].osu
2021/06/23 20:30:10 Trying to load storyboard from:  C:\Users\TiMoFey\AppData\Local\osu!\Songs\1316097 Kaede To Kyo Aki Ame Kuzu - Q\Kaede To Kyo Aki Ame Kuzu - Q (Abelia).osb
2021/06/23 20:30:10 open C:\Users\TiMoFey\AppData\Local\osu!\Songs\1316097 Kaede To Kyo Aki Ame Kuzu - Q\Kaede To Kyo Aki Ame Kuzu - Q (Abelia).osb: The system cannot find the file specified.
2021/06/23 20:30:10 Storyboard not found!
2021/06/23 20:30:10 Creating HitObject container...
2021/06/23 20:30:10 Audio track: audio.mp3
2021/06/23 20:30:10 SkinManager: Texture uploaded as single texture: spinner-background.png
2021/06/23 20:30:10 SkinManager: Texture uploaded as single texture: spinner-metre.png
panic: Audio codec "aac" does not exist

goroutine 19 [running]:
github.com/wieku/danser-go/app/ffmpeg.precheck()
        D:/danser-go/app/ffmpeg/ffmpeg.go:102 +0x5d7
github.com/wieku/danser-go/app/ffmpeg.StartFFmpeg(0x3c, 0x780, 0x438)
        D:/danser-go/app/ffmpeg/ffmpeg.go:107 +0x46
main.mainLoopRecord()
        D:/danser-go/main.go:550 +0x1d1
main.run()
        D:/danser-go/main.go:525 +0x65
github.com/faiface/mainthread.Run.func1(0x7ff6e1fde448, 0xc0000c70e0)
        C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x2e
created by github.com/faiface/mainthread.Run
        C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xab

C:\Users\TiMoFey>

**Computer configuration:**
Operating System: Windows 10
CPU: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz, 4 cores
GPU: Intel(R) HD Graphics 620

**Comment by vladaad** [comment] 2021-06-23 17:44
Send the output of `ffmpeg -encoders`

**Comment by Wieku** [comment] 2021-06-29 00:27
Closing this as it's probably caused by incorrect/outdated ffmpeg.

**Closed by Wieku** 2021-06-29 00:27 UTC
Labels: question
