### ISSUE TITLE
Stable replay passed but danser will fail and spinning value wrong

### ISSUE THREAD

**Issue by Oading** [Wieku/danser-go#342] opened 2023-08-26 14:53 UTC
Replay fails even when stable doesnt
danser version:0.8.4
video:https://www.bilibili.com/video/BV1Gw411Q7Gm/
replay:
[Oading - GALNERYUS - ULTIMATE SACRIFICE [The Sword of Promised Victory] (2023-08-23) Osu-4.zip](https://github.com/Wieku/danser-go/files/12445592/Oading.-.GALNERYUS.-.ULTIMATE.SACRIFICE.The.Sword.of.Promised.Victory.2023-08-23.Osu-4.zip)
even i open the IgnoreFailsInReplays will give one spinning very high value
![屏幕截图 2023-08-26 225052](https://github.com/Wieku/danser-go/assets/16524914/15ab60c6-f3e5-4e86-b768-70f1748fad16)

**Comment by Wieku** [comment] 2023-09-12 01:53
Well, what can I say... danser is not bound to be perfect 100% with judgements, but terrible play definitely doesn't help.

Possible duplicate of #316 
Spinner stuff is covered by #330

**Closed by Wieku** 2023-09-12 01:53 UTC
